<?php //All Customer Feedback Page ;
/**
 * @var Esca7a\ModuleDataBase\Block\ResourceCollectionData $block;
 * create connect fields to /ModuleDataBase//index;
 * here we use *instance of classes @block file
 */
?>

<html>
<style>
    @import url('https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700');

    $base-spacing-unit: 24px;
    $half-spacing-unit: $base-spacing-unit / 2;

    $color-alpha: #1772FF;
    $color-form-highlight: #EEEEEE;

    *, *:before, *:after {
        box-sizing:border-box;
    }

    body {
        padding:$base-spacing-unit;
        font-family:'Source Sans Pro', sans-serif;
        margin:0;
    }

    h1,h2,h3,h4,h5,h6 {
        margin:0;
    }

    .container {
        max-width: 1000px;
        margin-right:auto;
        margin-left:auto;
        display:flex;
        justify-content:center;
        align-items:center;
        min-height:100vh;
    }

    .table {
        width:100%;
        border:1px solid $color-form-highlight;
    }

    .table-header {
        display:flex;
        width:100%;
        background:#000;
        padding:($half-spacing-unit * 1.5) 0;
    }

    .table-row {
        display:flex;
        width:100%;
        padding:($half-spacing-unit * 1.5) 0;

    &:nth-of-type(odd) {
         background:$color-form-highlight;
     }
    }

    .table-data, .header__item {
        flex: 1 1 20%;
        text-align:center;
    }

    .header__item {
        text-transform:uppercase;
    }

    .filter__link {
        color:white;
        text-decoration: none;
        position:relative;
        display:inline-block;
        padding-left:$base-spacing-unit;
        padding-right:$base-spacing-unit;

    &::after {
         content:'';
         position:absolute;
         right:-($half-spacing-unit * 1.5);
         color:white;
         font-size:$half-spacing-unit;
         top: 50%;
         transform: translateY(-50%);
     }

    &.desc::after {
         content: '(desc)';
     }

    &.asc::after {
         content: '(asc)';
     }

    }
</style>
<script type="text/javascript">
    const properties = [
        'requestNum',
        'itemName',
        'serialNum',
        'detail',
        'requestDate',
    ];

    $.each( properties, function( i, val ) {

        let orderClass = '';

        $("#" + val).click(function(e){
            e.preventDefault();
            $('.filter__link.filter__link--active').not(this).removeClass('filter__link--active');
            $(this).toggleClass('filter__link--active');
            $('.filter__link').removeClass('asc desc');

            if(orderClass == 'desc' || orderClass == '') {
                $(this).addClass('asc');
                orderClass = 'asc';
            } else {
                $(this).addClass('desc');
                orderClass = 'desc';
            }

            let parent = $(this).closest('.header__item');
            let index = $(".header__item").index(parent);
            let $table = $('.table-content');
            let rows = $table.find('.table-row').get();
            let isSelected = $(this).hasClass('filter__link--active');
            let isNumber = $(this).hasClass('filter__link--number');

            rows.sort(function(a, b){

                let x = $(a).find('.table-data').eq(index).text();
                let y = $(b).find('.table-data').eq(index).text();

                if(isNumber == true) {

                    if(isSelected) {
                        return x - y;
                    } else {
                        return y - x;
                    }

                } else {

                    if(isSelected) {
                        if(x < y) return -1;
                        if(x > y) return 1;
                        return 0;
                    } else {
                        if(x > y) return -1;
                        if(x < y) return 1;
                        return 0;
                    }
                }
            });

            $.each(rows, function(index,row) {
                $table.append(row);
            });

            return false;
        });

    });
</script>
    <div>
        <p>Hello (username)! That's the list of your requests!</p>
    </div>
    <div class="container">
        <div class="table">
            <div class="table-header">
                <div class="header__item">
                    <a id="requestNum" class="filter__link" href="#" >number of request</a>
                </div>
                <div class="header__item">
                    <a id="itemName" class="filter__link filter__link--number" href="#">Product name</a>
                </div>
                <div class="header__item">
                    <a id="serialNum" class="filter__link filter__link--number" href="#">Serial Number</a>
                </div>
                <div class="header__item">
                    <a id="detail" class="filter__link filter__link--number" href="#">Detail</a>
                </div>
                <div class="header__item">
                    <a id="requestDate" class="filter__link filter__link--number" href="#">Request date</a>
                </div>
            </div>
            <?php
            $customerId = $block->getCustomerId();
            $collection = $block->getCollection();
            foreach ($collection as $item) {
                $data = [
                    'application_id' => $item->getData('application_id'),
                    'customer_id' => $item->getData('customer_id'),
                    'product_name' => $item->getData('product_name'),
                    'serial_number' => $item->getData('serial_number'),
                    'user_request' => $item->getData('user_request'),
                    'created_at' => $item->getData('created_at')
                ]; ?>
            <div class="table-content">
                <?php if (in_array($customerId, $data)): ?>
                <div class="table-row" style="border-bottom: 1px solid">
                    <div class="table-data" style="border-right-style: solid; border-left-style: solid">
                        <?php echo $data['application_id']?>
                    </div>
                    <div class="table-data" style="border-right-style: solid; border-left-style: solid">
                        <?php echo $data['product_name']?>
                    </div>
                    <div class="table-data" style="border-right-style: solid; border-left-style: solid">
                        <?php echo $data['serial_number']?>
                    </div>
                    <div class="table-data" style="border-right-style: solid; border-left-style: solid">
                        <?php echo $data['user_request']?>
                    </div>
                    <div class="table-data" style="border-right-style: solid; border-left-style: solid">
                        <?php echo $data['created_at']?>
                    </div>
                </div>
            </div>
            <?php
            endif;
            }
            ?>
        </div>
    </div>
</html>
